# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clinostat.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 575)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(659, 10, 350, 350))
        self.Image_Frame.setToolTip("")
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(3)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/Background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 631, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.Lighting_tab = QtWidgets.QWidget()
        self.Lighting_tab.setObjectName("Lighting_tab")
        self.frame = QtWidgets.QFrame(self.Lighting_tab)
        self.frame.setGeometry(QtCore.QRect(0, 20, 411, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.coreImage = QtWidgets.QLabel(self.frame)
        self.coreImage.setGeometry(QtCore.QRect(70, 15, 270, 270))
        self.coreImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.coreImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.coreImage.setText("")
        self.coreImage.setPixmap(QtGui.QPixmap("../_image/insert.png"))
        self.coreImage.setScaledContents(True)
        self.coreImage.setObjectName("coreImage")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 300, 371, 191))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 112, 351, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.W_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.W_spinBox.setMaximum(100)
        self.W_spinBox.setObjectName("W_spinBox")
        self.gridLayout.addWidget(self.W_spinBox, 1, 3, 1, 1)
        self.W_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.W_label.setObjectName("W_label")
        self.gridLayout.addWidget(self.W_label, 1, 2, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 0, 0, 1, 1)
        self.B_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 1, 0, 1, 1)
        self.B_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B_spinBox.setMaximum(100)
        self.B_spinBox.setObjectName("B_spinBox")
        self.gridLayout.addWidget(self.B_spinBox, 1, 1, 1, 1)
        self.R_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.R_spinBox.setMaximum(100)
        self.R_spinBox.setProperty("value", 50)
        self.R_spinBox.setObjectName("R_spinBox")
        self.gridLayout.addWidget(self.R_spinBox, 0, 1, 1, 1)
        self.G_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 2, 1, 1)
        self.G_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.G_spinBox.setMaximum(100)
        self.G_spinBox.setObjectName("G_spinBox")
        self.gridLayout.addWidget(self.G_spinBox, 0, 3, 1, 1)
        self.light_Confirm_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Confirm_pushButton.setObjectName("light_Confirm_pushButton")
        self.gridLayout.addWidget(self.light_Confirm_pushButton, 1, 4, 1, 1)
        self.light_Reset_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Reset_pushButton.setObjectName("light_Reset_pushButton")
        self.gridLayout.addWidget(self.light_Reset_pushButton, 0, 4, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.frame_5)
        self.line_13.setGeometry(QtCore.QRect(10, 85, 351, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 351, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Start_label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Start_label_3.setObjectName("Start_label_3")
        self.gridLayout_3.addWidget(self.Start_label_3, 2, 1, 1, 1)
        self.Start_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Start_label.setObjectName("Start_label")
        self.gridLayout_3.addWidget(self.Start_label, 2, 0, 1, 1)
        self.BRT_lable = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.BRT_lable.setObjectName("BRT_lable")
        self.gridLayout_3.addWidget(self.BRT_lable, 2, 2, 1, 1)
        self.Address_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Address_label.setObjectName("Address_label")
        self.gridLayout_3.addWidget(self.Address_label, 1, 1, 1, 1)
        self.Start_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.Start_spinBox.setMinimum(1)
        self.Start_spinBox.setMaximum(85)
        self.Start_spinBox.setObjectName("Start_spinBox")
        self.gridLayout_3.addWidget(self.Start_spinBox, 3, 0, 1, 1)
        self.End_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.End_spinBox.setMinimum(2)
        self.End_spinBox.setMaximum(86)
        self.End_spinBox.setProperty("value", 86)
        self.End_spinBox.setObjectName("End_spinBox")
        self.gridLayout_3.addWidget(self.End_spinBox, 3, 1, 1, 1)
        self.BRT_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.BRT_spinBox.setMinimum(1)
        self.BRT_spinBox.setMaximum(150)
        self.BRT_spinBox.setProperty("value", 50)
        self.BRT_spinBox.setObjectName("BRT_spinBox")
        self.gridLayout_3.addWidget(self.BRT_spinBox, 3, 2, 1, 1)
        self.color_label = QtWidgets.QLabel(self.frame_5)
        self.color_label.setGeometry(QtCore.QRect(150, 100, 79, 13))
        self.color_label.setObjectName("color_label")
        self.frame_2 = QtWidgets.QFrame(self.Lighting_tab)
        self.frame_2.setGeometry(QtCore.QRect(420, 120, 191, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 171, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lightCycle_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lightCycle_label.setObjectName("lightCycle_label")
        self.verticalLayout_18.addWidget(self.lightCycle_label)
        self.Cycle_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Cycle_label.setObjectName("Cycle_label")
        self.verticalLayout_18.addWidget(self.Cycle_label)
        self.powerCycle_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.powerCycle_spinBox.setMinimum(1)
        self.powerCycle_spinBox.setMaximum(999999999)
        self.powerCycle_spinBox.setProperty("value", 60)
        self.powerCycle_spinBox.setObjectName("powerCycle_spinBox")
        self.verticalLayout_18.addWidget(self.powerCycle_spinBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem)
        self.confirmCycle_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.confirmCycle_pushButton.setObjectName("confirmCycle_pushButton")
        self.verticalLayout_18.addWidget(self.confirmCycle_pushButton)
        self.IR_pushButton = QtWidgets.QPushButton(self.Lighting_tab)
        self.IR_pushButton.setGeometry(QtCore.QRect(450, 380, 141, 51))
        self.IR_pushButton.setObjectName("IR_pushButton")
        self.infraredImaging_checkBox = QtWidgets.QCheckBox(self.Lighting_tab)
        self.infraredImaging_checkBox.setEnabled(True)
        self.infraredImaging_checkBox.setGeometry(QtCore.QRect(450, 440, 161, 41))
        self.infraredImaging_checkBox.setObjectName("infraredImaging_checkBox")
        self.tabWidget.addTab(self.Lighting_tab, "")
        self.Frame_tab = QtWidgets.QWidget()
        self.Frame_tab.setObjectName("Frame_tab")
        self.frameReverse_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.frameReverse_pushButton.setGeometry(QtCore.QRect(90, 370, 41, 41))
        self.frameReverse_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../_image/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frameReverse_pushButton.setIcon(icon1)
        self.frameReverse_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.frameReverse_pushButton.setObjectName("frameReverse_pushButton")
        self.link_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.link_pushButton.setGeometry(QtCore.QRect(280, 210, 50, 50))
        self.link_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../_image/Link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.link_pushButton.setIcon(icon2)
        self.link_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.link_pushButton.setCheckable(False)
        self.link_pushButton.setObjectName("link_pushButton")
        self.coreReverse_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.coreReverse_pushButton.setGeometry(QtCore.QRect(540, 370, 41, 41))
        self.coreReverse_pushButton.setText("")
        self.coreReverse_pushButton.setIcon(icon1)
        self.coreReverse_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.coreReverse_pushButton.setObjectName("coreReverse_pushButton")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Frame_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(130, 10, 81, 401))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.frame_label.setObjectName("frame_label")
        self.verticalLayout_20.addWidget(self.frame_label)
        self.frame_verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.frame_verticalSlider.setMinimum(2)
        self.frame_verticalSlider.setMaximum(60)
        self.frame_verticalSlider.setSingleStep(1)
        self.frame_verticalSlider.setPageStep(2)
        self.frame_verticalSlider.setProperty("value", 10)
        self.frame_verticalSlider.setSliderPosition(10)
        self.frame_verticalSlider.setTracking(True)
        self.frame_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.frame_verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.frame_verticalSlider.setTickInterval(1)
        self.frame_verticalSlider.setObjectName("frame_verticalSlider")
        self.verticalLayout_20.addWidget(self.frame_verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.Frame_tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(460, 10, 81, 401))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.core_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.core_label.setObjectName("core_label")
        self.verticalLayout_22.addWidget(self.core_label)
        self.core_verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_8)
        self.core_verticalSlider.setMinimum(2)
        self.core_verticalSlider.setMaximum(60)
        self.core_verticalSlider.setSingleStep(1)
        self.core_verticalSlider.setPageStep(2)
        self.core_verticalSlider.setProperty("value", 10)
        self.core_verticalSlider.setSliderPosition(10)
        self.core_verticalSlider.setTracking(True)
        self.core_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.core_verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.core_verticalSlider.setTickInterval(1)
        self.core_verticalSlider.setObjectName("core_verticalSlider")
        self.verticalLayout_22.addWidget(self.core_verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.frameErgz_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.frameErgz_pushButton.setGeometry(QtCore.QRect(100, 462, 149, 41))
        self.frameErgz_pushButton.setObjectName("frameErgz_pushButton")
        self.frame_spinBox = QtWidgets.QDoubleSpinBox(self.Frame_tab)
        self.frame_spinBox.setEnabled(True)
        self.frame_spinBox.setGeometry(QtCore.QRect(100, 419, 149, 31))
        self.frame_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_spinBox.setReadOnly(False)
        self.frame_spinBox.setDecimals(2)
        self.frame_spinBox.setMinimum(0.1)
        self.frame_spinBox.setMaximum(3.5)
        self.frame_spinBox.setSingleStep(0.05)
        self.frame_spinBox.setProperty("value", 0.5)
        self.frame_spinBox.setObjectName("frame_spinBox")
        self.core_spinBox = QtWidgets.QDoubleSpinBox(self.Frame_tab)
        self.core_spinBox.setEnabled(True)
        self.core_spinBox.setGeometry(QtCore.QRect(420, 419, 149, 31))
        self.core_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.core_spinBox.setDecimals(2)
        self.core_spinBox.setMinimum(0.1)
        self.core_spinBox.setMaximum(3.5)
        self.core_spinBox.setSingleStep(0.05)
        self.core_spinBox.setProperty("value", 0.5)
        self.core_spinBox.setObjectName("core_spinBox")
        self.coreErgz_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.coreErgz_pushButton.setGeometry(QtCore.QRect(420, 462, 149, 41))
        self.coreErgz_pushButton.setObjectName("coreErgz_pushButton")
        self.line = QtWidgets.QFrame(self.Frame_tab)
        self.line.setGeometry(QtCore.QRect(280, 280, 51, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Frame_tab)
        self.line_2.setGeometry(QtCore.QRect(280, 20, 51, 171))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.Frame_tab, "")
        self.Imaging_tab = QtWidgets.QWidget()
        self.Imaging_tab.setObjectName("Imaging_tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Imaging_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 611, 241))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Image_Title = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Title.setObjectName("Image_Title")
        self.verticalLayout.addWidget(self.Image_Title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.title_lineEdit.setEnabled(True)
        self.title_lineEdit.setToolTip("")
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.horizontalLayout_2.addWidget(self.title_lineEdit)
        self.addDate_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.addDate_pushButton.setEnabled(False)
        self.addDate_pushButton.setObjectName("addDate_pushButton")
        self.horizontalLayout_2.addWidget(self.addDate_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.Image_Interval = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Interval.setObjectName("Image_Interval")
        self.verticalLayout.addWidget(self.Image_Interval)
        self.ICI_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ICI_spinBox.setEnabled(True)
        self.ICI_spinBox.setMinimum(2)
        self.ICI_spinBox.setMaximum(99999999)
        self.ICI_spinBox.setProperty("value", 2)
        self.ICI_spinBox.setObjectName("ICI_spinBox")
        self.verticalLayout.addWidget(self.ICI_spinBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Image_Duration = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Duration.setObjectName("Image_Duration")
        self.verticalLayout_2.addWidget(self.Image_Duration)
        self.ISD_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ISD_spinBox.setEnabled(True)
        self.ISD_spinBox.setMinimum(2)
        self.ISD_spinBox.setMaximum(99999999)
        self.ISD_spinBox.setProperty("value", 2)
        self.ISD_spinBox.setObjectName("ISD_spinBox")
        self.verticalLayout_2.addWidget(self.ISD_spinBox)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.directory_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.directory_label.setEnabled(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.directory_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.directory_label.setObjectName("directory_label")
        self.verticalLayout_2.addWidget(self.directory_label)
        self.directory_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.directory_pushButton.setEnabled(True)
        self.directory_pushButton.setCheckable(False)
        self.directory_pushButton.setObjectName("directory_pushButton")
        self.verticalLayout_2.addWidget(self.directory_pushButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget = QtWidgets.QWidget(self.Imaging_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 440, 611, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_6.addWidget(self.Progress_Label, 0, QtCore.Qt.AlignHCenter)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_6.addWidget(self.Progress_Bar)
        self.frame_3 = QtWidgets.QFrame(self.Imaging_tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 280, 611, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Imaging_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 290, 591, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CoreCtr_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_6.setObjectName("CoreCtr_label_6")
        self.gridLayout_2.addWidget(self.CoreCtr_label_6, 3, 2, 1, 1)
        self.yAxis_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.yAxis_label.setObjectName("yAxis_label")
        self.gridLayout_2.addWidget(self.yAxis_label, 3, 4, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.resolution_label.setObjectName("resolution_label")
        self.gridLayout_2.addWidget(self.resolution_label, 0, 2, 1, 1)
        self.xAxis_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.xAxis_label.setObjectName("xAxis_label")
        self.gridLayout_2.addWidget(self.xAxis_label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.x_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.x_resolution_spinBox.setMinimum(50)
        self.x_resolution_spinBox.setMaximum(3240)
        self.x_resolution_spinBox.setProperty("value", 2464)
        self.x_resolution_spinBox.setObjectName("x_resolution_spinBox")
        self.gridLayout_2.addWidget(self.x_resolution_spinBox, 1, 0, 1, 1)
        self.PNG_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.PNG_radioButton.setObjectName("PNG_radioButton")
        self.gridLayout_2.addWidget(self.PNG_radioButton, 6, 3, 1, 1)
        self.resolution_label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.resolution_label_2.setObjectName("resolution_label_2")
        self.gridLayout_2.addWidget(self.resolution_label_2, 5, 2, 1, 1)
        self.y_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.y_resolution_spinBox.setMinimum(50)
        self.y_resolution_spinBox.setMaximum(2464)
        self.y_resolution_spinBox.setProperty("value", 2464)
        self.y_resolution_spinBox.setObjectName("y_resolution_spinBox")
        self.gridLayout_2.addWidget(self.y_resolution_spinBox, 1, 3, 1, 1)
        self.JPG_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.JPG_radioButton.setChecked(True)
        self.JPG_radioButton.setObjectName("JPG_radioButton")
        self.gridLayout_2.addWidget(self.JPG_radioButton, 6, 0, 1, 1)
        self.resolution_label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.resolution_label_3.setObjectName("resolution_label_3")
        self.gridLayout_2.addWidget(self.resolution_label_3, 2, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 2, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 2, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 2, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 5, 3, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 5, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 2, 4, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 5, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 5, 4, 1, 1)
        self.xAxis_horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.xAxis_horizontalSlider.setMaximum(100)
        self.xAxis_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xAxis_horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.xAxis_horizontalSlider.setObjectName("xAxis_horizontalSlider")
        self.gridLayout_2.addWidget(self.xAxis_horizontalSlider, 3, 0, 1, 1)
        self.yAxis_horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.yAxis_horizontalSlider.setMinimum(1)
        self.yAxis_horizontalSlider.setMaximum(100)
        self.yAxis_horizontalSlider.setProperty("value", 100)
        self.yAxis_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yAxis_horizontalSlider.setInvertedAppearance(False)
        self.yAxis_horizontalSlider.setInvertedControls(False)
        self.yAxis_horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.yAxis_horizontalSlider.setObjectName("yAxis_horizontalSlider")
        self.gridLayout_2.addWidget(self.yAxis_horizontalSlider, 3, 3, 1, 1)
        self.tabWidget.addTab(self.Imaging_tab, "")
        self.Sensor_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.Sensor_tabWidget.setGeometry(QtCore.QRect(660, 390, 161, 111))
        self.Sensor_tabWidget.setObjectName("Sensor_tabWidget")
        self.ACC_tab = QtWidgets.QWidget()
        self.ACC_tab.setObjectName("ACC_tab")
        self.ACC_label = QtWidgets.QLabel(self.ACC_tab)
        self.ACC_label.setGeometry(QtCore.QRect(10, -10, 141, 31))
        self.ACC_label.setObjectName("ACC_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.ACC_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 151, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ACC_X_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_label.setObjectName("ACC_X_label")
        self.verticalLayout_4.addWidget(self.ACC_X_label)
        self.ACC_Y_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_label.setObjectName("ACC_Y_label")
        self.verticalLayout_4.addWidget(self.ACC_Y_label)
        self.ACC_Z_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_label.setObjectName("ACC_Z_label")
        self.verticalLayout_4.addWidget(self.ACC_Z_label)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ACC_X_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_text_label.setObjectName("ACC_X_text_label")
        self.verticalLayout_5.addWidget(self.ACC_X_text_label)
        self.ACC_Y_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_text_label.setObjectName("ACC_Y_text_label")
        self.verticalLayout_5.addWidget(self.ACC_Y_text_label)
        self.ACC_Z_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_text_label.setObjectName("ACC_Z_text_label")
        self.verticalLayout_5.addWidget(self.ACC_Z_text_label)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ACC_X_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_Unit_label.setObjectName("ACC_X_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_X_Unit_label)
        self.ACC_Y_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_Unit_label.setObjectName("ACC_Y_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_Y_Unit_label)
        self.ACC_Z_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_Unit_label.setObjectName("ACC_Z_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_Z_Unit_label)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.Sensor_tabWidget.addTab(self.ACC_tab, "")
        self.TEMP_tab = QtWidgets.QWidget()
        self.TEMP_tab.setObjectName("TEMP_tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TEMP_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 152, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TEMP_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.TEMP_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TEMP_label.setObjectName("TEMP_label")
        self.verticalLayout_8.addWidget(self.TEMP_label)
        self.HUM_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.HUM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.HUM_label.setObjectName("HUM_label")
        self.verticalLayout_8.addWidget(self.HUM_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.TEMP_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.TEMP_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TEMP_text_label.setObjectName("TEMP_text_label")
        self.verticalLayout_9.addWidget(self.TEMP_text_label)
        self.HUM_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.HUM_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.HUM_text_label.setObjectName("HUM_text_label")
        self.verticalLayout_9.addWidget(self.HUM_text_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.TEMP_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.TEMP_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.TEMP_Unit_label.setObjectName("TEMP_Unit_label")
        self.verticalLayout_10.addWidget(self.TEMP_Unit_label)
        self.HUM_Unit_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.HUM_Unit_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.HUM_Unit_label_2.setObjectName("HUM_Unit_label_2")
        self.verticalLayout_10.addWidget(self.HUM_Unit_label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.Sensor_tabWidget.addTab(self.TEMP_tab, "")
        self.PR_tab = QtWidgets.QWidget()
        self.PR_tab.setObjectName("PR_tab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.PR_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 152, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.PR_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.PR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PR_label.setObjectName("PR_label")
        self.verticalLayout_11.addWidget(self.PR_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.PR_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.PR_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PR_text_label.setObjectName("PR_text_label")
        self.verticalLayout_12.addWidget(self.PR_text_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.PR_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.PR_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PR_Unit_label.setObjectName("PR_Unit_label")
        self.verticalLayout_13.addWidget(self.PR_Unit_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.Sensor_tabWidget.addTab(self.PR_tab, "")
        self.core_status_label = QtWidgets.QLabel(self.centralwidget)
        self.core_status_label.setGeometry(QtCore.QRect(660, 360, 191, 31))
        self.core_status_label.setObjectName("core_status_label")
        self.Capture_frame = QtWidgets.QFrame(self.centralwidget)
        self.Capture_frame.setEnabled(True)
        self.Capture_frame.setGeometry(QtCore.QRect(830, 370, 181, 191))
        self.Capture_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Capture_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Capture_frame.setObjectName("Capture_frame")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Capture_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 161, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.snapshot_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.snapshot_pushButton.setEnabled(True)
        self.snapshot_pushButton.setObjectName("snapshot_pushButton")
        self.verticalLayout_17.addWidget(self.snapshot_pushButton)
        self.preview_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.verticalLayout_17.addWidget(self.preview_pushButton)
        self.rotate_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.rotate_pushButton.setEnabled(True)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_17.addWidget(self.rotate_pushButton)
        self.startImaging_pushButton = QtWidgets.QPushButton(self.Capture_frame)
        self.startImaging_pushButton.setEnabled(False)
        self.startImaging_pushButton.setGeometry(QtCore.QRect(10, 120, 161, 61))
        self.startImaging_pushButton.setToolTip("")
        self.startImaging_pushButton.setObjectName("startImaging_pushButton")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(660, 500, 161, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.log_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.log_spinBox.setMinimum(1)
        self.log_spinBox.setObjectName("log_spinBox")
        self.gridLayout_5.addWidget(self.log_spinBox, 1, 1, 1, 1)
        self.log_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.log_pushButton.setObjectName("log_pushButton")
        self.gridLayout_5.addWidget(self.log_pushButton, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.sample_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.sample_doubleSpinBox.setDecimals(1)
        self.sample_doubleSpinBox.setMinimum(0.1)
        self.sample_doubleSpinBox.setSingleStep(0.1)
        self.sample_doubleSpinBox.setObjectName("sample_doubleSpinBox")
        self.gridLayout_5.addWidget(self.sample_doubleSpinBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Sensor_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SciSpiner MAX"))
        self.W_spinBox.setToolTip(_translate("MainWindow", "Warm White Color Intensity, note that at high brightnesses  warm white LEDs consume a considerable more amount of power than the other color LEDs"))
        self.W_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.W_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">W White:</span></p></body></html>"))
        self.R_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Red:</span></p></body></html>"))
        self.B_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Blue:</span></p></body></html>"))
        self.B_spinBox.setToolTip(_translate("MainWindow", "Blue Color Intensity"))
        self.B_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.R_spinBox.setToolTip(_translate("MainWindow", "Red Color Intensity"))
        self.R_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.G_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Green:</span></p></body></html>"))
        self.G_spinBox.setToolTip(_translate("MainWindow", "Green Color Intensity"))
        self.G_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.light_Confirm_pushButton.setToolTip(_translate("MainWindow", "Confirm current light settings."))
        self.light_Confirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.light_Reset_pushButton.setToolTip(_translate("MainWindow", "Turn off all LEDs and restore settings to default."))
        self.light_Reset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.Start_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">End LED: </span><span style=\" font-size:7pt; font-weight:600;\">[2 , 86]</span></p></body></html>"))
        self.Start_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Start LED: </span><span style=\" font-size:7pt; font-weight:600;\">[1 , 85]</span></p></body></html>"))
        self.BRT_lable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Brightness: </span><span style=\" font-size:7pt; font-weight:600;\">[0 , 150]</span></p></body></html>"))
        self.Address_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LED Settings</span></p></body></html>"))
        self.Start_spinBox.setToolTip(_translate("MainWindow", "The first LED that you wish to control [1,84]"))
        self.Start_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.End_spinBox.setToolTip(_translate("MainWindow", "The Last LED that you wish to control [2,84]"))
        self.End_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.BRT_spinBox.setToolTip(_translate("MainWindow", "General Brightness of all visible light LEDs, internal temperature may rise if both the number of LEDs and the brightness are set high"))
        self.BRT_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color Settings</span></p></body></html>"))
        self.lightCycle_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Power Cycle</span></p></body></html>"))
        self.Cycle_label.setText(_translate("MainWindow", "Cycle Duration:"))
        self.powerCycle_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.confirmCycle_pushButton.setToolTip(_translate("MainWindow", "All LEDs are toggled at the end of each cycle"))
        self.confirmCycle_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.IR_pushButton.setToolTip(_translate("MainWindow", "Control Infrared LEDs"))
        self.IR_pushButton.setText(_translate("MainWindow", "IR STATUS:OFF"))
        self.infraredImaging_checkBox.setToolTip(_translate("MainWindow", "Briefly switch off all visible light LEDs and toggle on infrared LEDs during imaging, light is restored afterwards (coming soon...)"))
        self.infraredImaging_checkBox.setText(_translate("MainWindow", "Infrared Imaging"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Lighting_tab), _translate("MainWindow", "LIGHTING"))
        self.frameReverse_pushButton.setToolTip(_translate("MainWindow", "Reverse rotation direction"))
        self.link_pushButton.setToolTip(_translate("MainWindow", "Sync or desync motor controls"))
        self.coreReverse_pushButton.setToolTip(_translate("MainWindow", "Reverse rotation direction"))
        self.frame_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Motor 1</span></p></body></html>"))
        self.core_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Motor 2</span></p></body></html>"))
        self.frameErgz_pushButton.setToolTip(_translate("MainWindow", "Enable or disable motor driver"))
        self.frameErgz_pushButton.setText(_translate("MainWindow", "ENABLE MOTOR"))
        self.frame_spinBox.setSuffix(_translate("MainWindow", " RPM"))
        self.core_spinBox.setSuffix(_translate("MainWindow", " RPM"))
        self.coreErgz_pushButton.setToolTip(_translate("MainWindow", "Enable or disable motor driver"))
        self.coreErgz_pushButton.setText(_translate("MainWindow", "ENABLE MOTOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frame_tab), _translate("MainWindow", "MOTION"))
        self.Image_Title.setText(_translate("MainWindow", "Image Sequence Title"))
        self.addDate_pushButton.setText(_translate("MainWindow", "Add Date"))
        self.Image_Interval.setText(_translate("MainWindow", "Image Capture Interval"))
        self.ICI_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Image_Duration.setText(_translate("MainWindow", "Image Sequence Duration"))
        self.ISD_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.directory_label.setText(_translate("MainWindow", "Sequence Title Required"))
        self.directory_pushButton.setText(_translate("MainWindow", "Select Storage Directory"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress: 0 / 1"))
        self.CoreCtr_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.yAxis_label.setText(_translate("MainWindow", "Zoom Axis B: 1.00"))
        self.resolution_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Imaging Resulution</span></p></body></html>"))
        self.xAxis_label.setText(_translate("MainWindow", "Zoom Axis A: 0.00"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 2464 ]</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 3240 ]</span></p></body></html>"))
        self.x_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.PNG_radioButton.setText(_translate("MainWindow", ".PNG"))
        self.resolution_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Image Format</span></p></body></html>"))
        self.y_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.JPG_radioButton.setText(_translate("MainWindow", ".JPG"))
        self.resolution_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Zoom Control</span></p></body></html>"))
        self.xAxis_horizontalSlider.setToolTip(_translate("MainWindow", "Zoom controls, snapshot is taken when released, useful during focusing"))
        self.yAxis_horizontalSlider.setToolTip(_translate("MainWindow", "Zoom controls, snapshot is taken when released, useful during focusing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Imaging_tab), _translate("MainWindow", "IMAGING"))
        self.Sensor_tabWidget.setToolTip(_translate("MainWindow", "9-DOF Sensor - FXOS8700 + FXAS21002"))
        self.ACC_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Accelerometer</span></p></body></html>"))
        self.ACC_X_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X:</span></p></body></html>"))
        self.ACC_Y_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y:</span></p></body></html>"))
        self.ACC_Z_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z:</span></p></body></html>"))
        self.ACC_X_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_Y_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_Z_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_X_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.ACC_Y_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.ACC_Z_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.ACC_tab), _translate("MainWindow", "ACC"))
        self.TEMP_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Temperature</span></p></body></html>"))
        self.HUM_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Humidity</span></p></body></html>"))
        self.TEMP_text_label.setText(_translate("MainWindow", "offline"))
        self.HUM_text_label.setText(_translate("MainWindow", "offline"))
        self.TEMP_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">°C</span></p></body></html>"))
        self.HUM_Unit_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">%</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.TEMP_tab), _translate("MainWindow", "TEMP"))
        self.PR_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Pressure</span></p></body></html>"))
        self.PR_text_label.setText(_translate("MainWindow", "offline"))
        self.PR_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">hPa</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.PR_tab), _translate("MainWindow", "PR"))
        self.core_status_label.setText(_translate("MainWindow", "Core Status: OFFLINE"))
        self.snapshot_pushButton.setToolTip(_translate("MainWindow", "Takes a quick snapshot"))
        self.snapshot_pushButton.setText(_translate("MainWindow", "SNAPSHOT"))
        self.preview_pushButton.setToolTip(_translate("MainWindow", "Takes a image with current settings"))
        self.preview_pushButton.setText(_translate("MainWindow", "PREVIEW"))
        self.rotate_pushButton.setToolTip(_translate("MainWindow", "Rotate image 90 degrees"))
        self.rotate_pushButton.setText(_translate("MainWindow", "ROTATE IMAGE"))
        self.startImaging_pushButton.setText(_translate("MainWindow", "START TIMELAPSE"))
        self.log_spinBox.setToolTip(_translate("MainWindow", "total logging duration"))
        self.log_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.log_pushButton.setToolTip(_translate("MainWindow", "Start logging data, all logs are saved on the desktop"))
        self.log_pushButton.setText(_translate("MainWindow", "LOG FOR"))
        self.label.setText(_translate("MainWindow", "Sample Rate"))
        self.sample_doubleSpinBox.setToolTip(_translate("MainWindow", "Time between each sample"))
        self.sample_doubleSpinBox.setSuffix(_translate("MainWindow", " s"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))
